services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: /api/v1
    ports:
      - '${FRONTEND_PORT:-5173}:5173'
    networks:
      - isep
networks:
  isep:
    driver: bridge
